//! `benchmarks/ipc-standings.md` -- the one-table-per-competition reference.
//! Port of `benchmarks/standings.py`'s `main()` (:761-1098).
//!
//! This is the document that says, for every board we hold, what was entered,
//! what it covered, in what currency it was scored, and how each unsolved row
//! failed. Five columns of prose, correct and unreadable at a glance -- which
//! is why `STANDINGS.md` exists beside it.
//!
//! Three things in here are incidents rather than layout, and each has its own
//! comment at the site:
//!
//! * **`seq-sat`, `tempo-sat` and `seq-opt` each appear TWICE**, once under
//!   IPC-6 and once under IPC-7, from ONE raw split on each row's own `ipc`
//!   field. The sweep is shared; the competitions are not.
//! * **An absent board renders one of two texts**, and they make opposite
//!   claims about the record -- see [`RenderCtx::absent_cell`].
//! * **The mco rows render their quality note even when absent.** The
//!   wall-clock rule is a DECISION, taken in 0.16 and re-affirmed for the 0.23
//!   re-entry, and it must be readable before the sweep lands rather than only
//!   after. Every other absent row renders em-dashes across.
//!
//! ## The prose belongs in the manifest
//!
//! The `const` tables below hold the document's SKELETON: section headings,
//! the column list, each board's `entered` text and each board's fixed quality
//! note. None of it is logic -- it is editorial copy about boards, and the
//! manifest (`benchmarks/manifest.toml`) is where facts about boards live.
//! `[[board]]` does not carry these fields yet, so they are here, in one place,
//! marked, so that moving them is a mechanical change with nothing to decide.
//! Until then: **a new board needs an entry in this file as well as the
//! manifest**, and a board missing from the render lists below cannot appear in
//! the table however completely it was swept -- 0.20 added `ipc2026-numeric` to
//! `SWEEPS` and not to the render list, and it was invisible for a cycle.

use crate::fmt::glyph;
use crate::quality::{bounds_wtl, length_wtl, makespan_wtl, QualityNote};
use crate::render::RenderCtx;

// ===========================================================================
// THE SKELETON -- belongs in benchmarks/manifest.toml; see the module header.
// ===========================================================================

/// The preamble. Six lines of prose, hard-wrapped exactly as the Python's list
/// literal wraps them -- the wrapping is in the committed artifact, so it is
/// content, not style.
const DOC_HEADER: &[&str] = &[
    "# IPC standings — the one honest table per competition",
    "",
    "Generated by `python3 benchmarks/standings.py` (do not hand-edit;",
    "regenerate after any sweep). Raw inputs are the per-instance JSONLs",
    "and the vendored official IPC-5 archive — see the module docstring",
    "for scoring semantics and the failure-class definitions.",
    "",
];

/// Every section's table header. One list, because a column added to one
/// competition and not another is a table that reads as two tables.
const TABLE_HEAD: &[&str] = &[
    "| track | entered | coverage | quality | failure classes |",
    "|---|---|---|---|---|",
];

const SECTION_IPC5: &str = "## IPC-5 (2006)";
const SECTION_IPC6: &str = "## IPC-6 (2008)";
const SECTION_IPC7: &str = "## IPC-7 (2011)";
const SECTION_MODERN: &str = "## The modern corpora (IPC 2014 / 2018 / 2023 — first entered 0.17)";

/// Which currency an IPC-5 board is scored in, and what its cell says when
/// nothing scores.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Ipc5Scoring {
    /// Plan LENGTH against the vendored archive field's lengths.
    Length,
    /// MAKESPAN against the archive field's, computed per `.soln` from the
    /// timed steps. Scored only on rows carrying the 0.22 makespan column.
    Makespan,
    /// Nothing to score against: the cell is its fixed note.
    Coverage,
}

/// The IPC-5 board rows, in render order, with their scoring currency and the
/// note that renders when the currency yields nothing.
///
/// The `time` / `metric-time` fallbacks name the 0.22 makespan column on
/// purpose: a raw that predates it renders coverage-only rather than a guessed
/// number, and the note says which of the two happened.
const IPC5_ROWS: &[(&str, Ipc5Scoring, &str)] = &[
    ("propositional", Ipc5Scoring::Length, "quality vs field"),
    (
        "time",
        Ipc5Scoring::Makespan,
        "coverage-only (raw predates the 0.22 makespan column)",
    ),
    (
        "metric-time",
        Ipc5Scoring::Makespan,
        "coverage-only (raw predates the 0.22 makespan column)",
    ),
    (
        "constraints",
        Ipc5Scoring::Coverage,
        "coverage-only (timed modal ops rejected by name)",
    ),
    (
        "simple-preferences (full corpus)",
        Ipc5Scoring::Coverage,
        "coverage = hard-goal solves; preference metric in the raw",
    ),
    (
        "qualitative-preferences (full corpus)",
        Ipc5Scoring::Coverage,
        "coverage = hard-goal solves; preference metric in the raw",
    ),
    (
        "complex-preferences (full corpus)",
        Ipc5Scoring::Coverage,
        "coverage = hard-goal solves; PDDL3 preference metric scored post-hoc \
         in the raw (0.25 Phase 2 entry)",
    ),
];

/// The three IPC-5 rows that are not boards at all.
///
/// The first two are reference-scored on their own curated 8-instance
/// scoreboards and are LINKED rather than recomputed here -- recomputing them
/// off a coverage sweep would replace a reference score with a different
/// measurement under the same name. The third records a feature gap: a track
/// entered as "no", which is a result.
const IPC5_TRAILER: &[&str] = &[
    "| simple-preferences | yes | see board | reference-scored — \
     [`ipc5-scoreboard.md`](ipc5-scoreboard.md) | — |",
    "| qualitative-preferences | yes | see board | reference-scored — \
     [`ipc5-qualitative-scoreboard.md`](ipc5-qualitative-scoreboard.md) \
     (24W/4T/10L vs SGPlan5 — ahead of the winner; rovers/storage/tpp won \
     outright) | — |",
    "| complex-preferences | no (modal operators rejected by name) | — | — | \
     feature gap, on the deferred list |",
];

/// The IPC-6 satisficing rows. Label and split key are the same string: the
/// board publishes under the name the competition gave the track.
const IPC6_TRACKS: &[&str] = &["seq-sat", "tempo-sat", "net-benefit"];
/// The IPC-7 satisficing rows. `net-benefit` is IPC-6 only.
const IPC7_TRACKS: &[&str] = &["seq-sat", "tempo-sat"];

const IPC_2008: &str = "ipc-2008";
const IPC_2011: &str = "ipc-2011";

/// IPC-6's quality note. The qualifier is the point: no official per-instance
/// archive is vendored for 2008/2011, so there is no field to score against and
/// the cell says so rather than leaving a reader to assume one.
const IPC6_QUALITY: &str = "coverage + VAL (no official per-instance archive vendored)";
/// IPC-7's, which the Python states without the qualifier.
const IPC7_QUALITY: &str = "coverage + VAL";

/// The shared `seq-opt` row, rendered once per competition off one raw.
const SEQ_OPT_ENTERED: &str = "yes (first entry, 0.19 — Mode::Optimal)";
const SEQ_OPT_QUALITY: &str = "coverage = PROOF RATE (A* + admissible LM-cut, h^max sprint \
                               first; every plan certified + VAL)";

/// The temporal optimal track: not absent, not swept -- excluded by design. A
/// blank row would read as a board we forgot.
const TEMPO_OPT_ROW: &str =
    "| tempo-opt | out of scope by design (satisficing temporal path) | — | — | — |";

/// The mco methodology, verbatim from the 0.16 decision.
///
/// 60 s WALL-CLOCK per the competition rule -- the track scores wall time on a
/// fixed box, however many cores a planner burns -- one instance at a time
/// (`--threads N --jobs 1`). t8 is oversubscribed by construction on the 4P+6E
/// Air and is recorded as such, not excused. This string renders on ABSENT mco
/// rows too; see the module header.
const MCO_QUALITY: &str = "wall-clock per competition rule (--threads N, one instance at a \
                           time; 4P+6E box — t8 oversubscribed by construction)";
const MCO_ENTERED: &str = "yes (first entry, 0.16)";
const IPC7_MCO: &[&str] = &["seq-mco t2", "seq-mco t4", "seq-mco t8"];

/// How a modern board's quality cell is produced.
#[derive(Debug, Clone, Copy)]
enum ModernQuality {
    /// Scored against the official best-known bounds file. `year_key` is
    /// TRACK-SCOPED (`"2023-agl"`, `"2023-sat"`), never a bare year: agl/, sat/
    /// and opt/ carry different instance sets under the same domain names, so a
    /// bare-year key would join a bound from one track onto an instance from
    /// another. When nothing scores, the cell is `"coverage-only"`.
    Bounds {
        year_key: &'static str,
        suffix: &'static str,
    },
    /// A fixed note -- the board has no scorable currency held here.
    Fixed(&'static str),
}

/// The proof-rate note the modern optimal boards share.
const PROOF_MODERN: &str = "coverage = PROOF RATE (Mode::Optimal, A* + admissible LM-cut, \
                            h^max sprint first; every plan certified + VAL)";
/// 0.25 Phase 1: the table grows. An ENTRY is not a movement -- no before/after
/// exists until its second cut, and the cell says so.
const ENTERED_25: &str = "yes (FIRST ENTRY, 0.25 — the table grows)";
const ENTERED_17: &str = "yes (first entry, 0.17)";
/// The one `entered` cell carrying the proof glyph inline.
///
/// Spelled with an escape rather than pasted, and written with `concat!`
/// because [`MODERN_ROWS`] is a `const` and cannot call `format!`. That is two
/// codepoints -- U+2696 SCALES and U+FE0F VARIATION SELECTOR-16 -- and the
/// selector is what asks for the emoji presentation. A hand-typed one-codepoint
/// `⚖` renders almost identically here and diffs against the committed table
/// with no number wrong to point at, which is why a test in this file checks
/// these bytes against [`glyph::SCALES`].
const ENTERED_2026_OPT: &str = concat!(
    "yes (FIRST ENTRY, 0.21 — the -opt pairs, ",
    "\u{2696}\u{fe0f}",
    ")"
);

/// Every modern board, in render order, with its quality rule and its `entered`
/// text.
///
/// THE RENDER LIST IS THE TABLE. A board absent from here cannot appear however
/// completely it was swept; 0.20 added `ipc2026-numeric` to the registry and not
/// to this list, and it was invisible for a cycle.
const MODERN_ROWS: &[(&str, ModernQuality, &str)] = &[
    (
        "2014 seq-sat",
        ModernQuality::Fixed("coverage + VAL"),
        ENTERED_17,
    ),
    (
        "2014 seq-agile",
        ModernQuality::Fixed("coverage + VAL"),
        ENTERED_17,
    ),
    (
        "2014 tempo-sat",
        ModernQuality::Fixed("coverage + VAL"),
        ENTERED_17,
    ),
    (
        "2014 seq-mco t2",
        ModernQuality::Fixed("wall-clock per competition rule (one instance at a time; 4P+6E box)"),
        ENTERED_25,
    ),
    (
        "2014 seq-mco t4",
        ModernQuality::Fixed(
            "wall-clock per competition rule (--threads 4, one instance at a time; \
             4P+6E box)",
        ),
        ENTERED_17,
    ),
    (
        "2014 seq-mco t8",
        ModernQuality::Fixed(
            "wall-clock per competition rule (one instance at a time; 4P+6E box, \
             t8 oversubscribed by construction)",
        ),
        ENTERED_25,
    ),
    (
        "2014 seq-opt",
        ModernQuality::Fixed(PROOF_MODERN),
        "yes (first entry, 0.19)",
    ),
    (
        "2018 seq-sat",
        ModernQuality::Bounds {
            year_key: "2018",
            suffix: "-sequential-satisficing",
        },
        ENTERED_17,
    ),
    (
        "2018 seq-opt",
        ModernQuality::Fixed(PROOF_MODERN),
        ENTERED_25,
    ),
    (
        "2023 classical",
        ModernQuality::Bounds {
            year_key: "2023-agl",
            suffix: "-agile",
        },
        ENTERED_17,
    ),
    (
        "2023 seq-sat",
        ModernQuality::Bounds {
            year_key: "2023-sat",
            suffix: "-satisficing",
        },
        ENTERED_25,
    ),
    (
        "2023 seq-opt",
        ModernQuality::Fixed(PROOF_MODERN),
        ENTERED_25,
    ),
    (
        "2023 agile ENTRY (300s)",
        ModernQuality::Fixed(
            "OFFICIAL 300 s budget — a competition-methodology ENTRY, not a baseline",
        ),
        "yes (OFFICIAL-BUDGET entry, 0.19)",
    ),
    (
        "2023 numeric",
        ModernQuality::Fixed(
            "field CSVs vendored (ipc-2023n/results) — per-domain comparison in the \
             audit record",
        ),
        ENTERED_17,
    ),
    (
        "2023 numeric-opt",
        ModernQuality::Fixed(
            "coverage = PROOF RATE over the numeric corpus; the track's official field \
             CSV (ipc-2023n/results/opt.csv) is the vs-field referee",
        ),
        ENTERED_25,
    ),
    (
        "2026 numeric (first board)",
        ModernQuality::Fixed(
            "coverage + VAL; the corpus ships -sat/-opt domain PAIRS, all swept \
             satisficing-style on this first board",
        ),
        // A blocked rider at 0.20 scoping (the organisers had not published),
        // swept for the first time here -- not a 0.17 board.
        "yes (FIRST ENTRY, 0.20 — new corpus)",
    ),
    (
        "2026 numeric-opt",
        ModernQuality::Fixed(
            "coverage = PROOF RATE (Mode::Optimal over the three -opt pairs; LENGTH \
             optima — the vendored corpus carries no active :metric; every \
             certificate VAL-checked)",
        ),
        ENTERED_2026_OPT,
    ),
    (
        "2026 numeric-opt FULL",
        ModernQuality::Fixed(
            "coverage = PROOF RATE over the official 13-domain/260 Overall Optimal \
             constituency (the 3-pair board above is the like-for-like slice)",
        ),
        ENTERED_25,
    ),
];

/// The closing note. The 2023 classical corpus is swept on its agile instances
/// at the standard satisficing budget, and the row is a BASELINE rather than a
/// competition entry -- stated because the competition's own agile budget is
/// five times larger and a reader who does not know that will read the coverage
/// as an entry's.
const MODERN_FOOTNOTE: &str = "The 2023 classical corpus is swept on its agile instances at \
                               the standard 60 s satisficing budget (the competition's agile \
                               budget is 300 s — these rows are BASELINES, marked as such, \
                               not competition entries).";

// ===========================================================================
// The renderer
// ===========================================================================

/// Render the whole document.
///
/// Returns a `String`; writes nothing. The Python's own comment calls a bare
/// in-place run "a destructive act" on a box holding only some of the raws, and
/// crucible does not inherit that -- the caller decides what to overwrite.
pub fn render(ctx: &RenderCtx) -> String {
    let mut l: Vec<String> = DOC_HEADER.iter().map(|s| (*s).to_string()).collect();

    section_ipc5(ctx, &mut l);
    section_ipc6(ctx, &mut l);
    section_ipc7(ctx, &mut l);
    section_modern(ctx, &mut l);

    // `"\n".join(lines) + "\n"`. The list ends with an empty string, so the
    // file ends with a blank line -- that trailing byte is in the committed
    // artifact and a "tidier" join drops it.
    let mut out = l.join("\n");
    out.push('\n');
    out
}

/// `| label | entered | — | — | — |` -- an absent board, every measured column
/// dashed. Only the mco rows deviate; they say why at their call site.
fn absent_row(label: &str, entered: &str) -> String {
    let d = glyph::EM_DASH;
    format!("| {label} | {entered} | {d} | {d} | {d} |")
}

fn open_table(l: &mut Vec<String>, heading: &str) {
    l.push(heading.to_string());
    l.push(String::new());
    l.extend(TABLE_HEAD.iter().map(|s| (*s).to_string()));
}

fn section_ipc5(ctx: &RenderCtx, l: &mut Vec<String>) {
    open_table(l, SECTION_IPC5);
    for (label, scoring, fallback) in IPC5_ROWS {
        let Some((rows, budget)) = ctx.data(label) else {
            l.push(absent_row(label, ctx.absent_cell(label)));
            continue;
        };
        let cov = ctx.coverage_of(rows, budget);
        // Python guards each scorer with `and arch` / `and arch_ms`. No guard
        // is needed: an empty archive misses every lookup, collects no ratio,
        // and `Wtl::build` declines -- so the fallback note renders by
        // construction rather than by a second test that could drift from it.
        let q = match scoring {
            Ipc5Scoring::Length => {
                QualityNote::new(length_wtl(rows, &ctx.referee, &ctx.archive), *fallback)
            }
            Ipc5Scoring::Makespan => {
                QualityNote::new(makespan_wtl(rows, &ctx.referee, &ctx.archive), *fallback)
            }
            Ipc5Scoring::Coverage => QualityNote::Fixed((*fallback).to_string()),
        };
        l.push(format!(
            "| {label} | yes | {}/{} | {} | {} |",
            cov.solved,
            cov.total,
            q.render(),
            cov.failure_classes()
        ));
    }
    l.extend(IPC5_TRAILER.iter().map(|s| (*s).to_string()));
    l.push(String::new());
}

fn section_ipc6(ctx: &RenderCtx, l: &mut Vec<String>) {
    open_table(l, SECTION_IPC6);
    for label in IPC6_TRACKS {
        push_split_row(ctx, l, label, IPC_2008, IPC6_QUALITY);
    }
    push_seq_opt_row(ctx, l, IPC_2008);
    l.push(TEMPO_OPT_ROW.to_string());
    l.push(String::new());
}

fn section_ipc7(ctx: &RenderCtx, l: &mut Vec<String>) {
    open_table(l, SECTION_IPC7);
    for label in IPC7_TRACKS {
        push_split_row(ctx, l, label, IPC_2011, IPC7_QUALITY);
    }
    for label in IPC7_MCO {
        let Some((rows, budget)) = ctx.data(label) else {
            // THE MCO QUIRK. An absent mco row still renders its quality note,
            // where every other absent row renders an em-dash. The wall-clock
            // rule is a DECISION about how the board will be measured, not a
            // result of measuring it, and it must be readable before the sweep
            // lands -- otherwise the methodology only becomes visible once it
            // no longer needs defending.
            l.push(format!(
                "| {label} | {} | {d} | {MCO_QUALITY} | {d} |",
                ctx.absent_cell(label),
                d = glyph::EM_DASH
            ));
            continue;
        };
        let cov = ctx.coverage_of(rows, budget);
        l.push(format!(
            "| {label} | {MCO_ENTERED} | {}/{} | {MCO_QUALITY} | {} |",
            cov.solved,
            cov.total,
            cov.failure_classes()
        ));
    }
    push_seq_opt_row(ctx, l, IPC_2011);
    l.push(String::new());
}

/// One row of a SHARED sweep, sliced to one competition.
///
/// `seq-sat`, `tempo-sat` and `net-benefit` are swept once and reported per
/// competition; the slice is each row's own `ipc` field, never the board's
/// name. An empty slice takes the absent branch -- a competition with no rows
/// in a shared raw was not measured at zero, it was not measured.
fn push_split_row(ctx: &RenderCtx, l: &mut Vec<String>, label: &str, ipc: &str, quality: &str) {
    let Some((rows, budget)) = ctx.split(label, ipc) else {
        l.push(absent_row(label, ctx.absent_cell(label)));
        return;
    };
    let cov = ctx.coverage_of(&rows, budget);
    l.push(format!(
        "| {label} | yes | {}/{} | {quality} | {} |",
        cov.solved,
        cov.total,
        cov.failure_classes()
    ));
}

/// The `seq-opt` row, which is the same board seen from two competitions.
fn push_seq_opt_row(ctx: &RenderCtx, l: &mut Vec<String>, ipc: &str) {
    let label = "seq-opt";
    let Some((rows, budget)) = ctx.split(label, ipc) else {
        l.push(absent_row(label, ctx.absent_cell(label)));
        return;
    };
    let cov = ctx.coverage_of(&rows, budget);
    l.push(format!(
        "| {label} | {SEQ_OPT_ENTERED} | {}/{} | {SEQ_OPT_QUALITY} | {} |",
        cov.solved,
        cov.total,
        cov.failure_classes()
    ));
}

fn section_modern(ctx: &RenderCtx, l: &mut Vec<String>) {
    open_table(l, SECTION_MODERN);
    for (label, quality, entered) in MODERN_ROWS {
        let Some((rows, budget)) = ctx.data(label) else {
            l.push(absent_row(label, ctx.absent_cell(label)));
            continue;
        };
        let cov = ctx.coverage_of(rows, budget);
        let q = match quality {
            ModernQuality::Bounds { year_key, suffix } => QualityNote::new(
                bounds_wtl(rows, &ctx.referee, &ctx.bounds, year_key, suffix),
                // The bounds files are gitignored corpus data. Absent, every
                // lookup misses and the board reports coverage-only rather than
                // a quality verdict it could not compute.
                "coverage-only",
            ),
            ModernQuality::Fixed(s) => QualityNote::Fixed((*s).to_string()),
        };
        l.push(format!(
            "| {label} | {entered} | {}/{} | {} | {} |",
            cov.solved,
            cov.total,
            q.render(),
            cov.failure_classes()
        ));
    }
    l.push(String::new());
    l.push(MODERN_FOOTNOTE.to_string());
    l.push(String::new());
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::tests_support::{absent_ctx, board_stanza, PREAMBLE};

    /// A manifest carrying just the boards a test names, all absent.
    fn ctx(boards: &[(&str, &str, &[&str])], box_: &str) -> crate::render::RenderCtx {
        let mut src = PREAMBLE.to_string();
        for (id, label, on) in boards {
            src.push_str(&board_stanza(id, label, on));
        }
        absent_ctx(&src, box_)
    }

    /// THE CLOUD-ERA BRANCH, which live data cannot reach: every label in this
    /// repository's manifest is rebaselined on `m5-air`, so today the renderer
    /// only ever takes the in-flight arm. Untested, the other arm ships as dead
    /// code and re-arms silently at the next hardware move -- and the two texts
    /// make OPPOSITE claims about the record. "Sweep in flight" on a board we
    /// have never measured on this box says a number is coming; "cloud-era" says
    /// the number exists and lives in git history.
    #[test]
    fn an_absent_board_never_swept_here_points_at_git_history() {
        let c = ctx(&[("ipc5-prop", "propositional", &[])], "m5-air");
        let out = render(&c);
        assert!(
            out.contains(
                "| propositional | cloud-era board, NOT re-baselined — see git history | — | — | — |"
            ),
            "{out}"
        );
    }

    /// The other arm, on the same board: this box HAS produced it, so a missing
    /// raw is a sweep that has not finished.
    #[test]
    fn an_absent_board_this_box_has_swept_reads_as_in_flight() {
        let c = ctx(&[("ipc5-prop", "propositional", &["m5-air"])], "m5-air");
        let out = render(&c);
        assert!(
            out.contains("| propositional | sweep in flight / not yet run | — | — | — |"),
            "{out}"
        );
    }

    /// THE MCO QUIRK. An absent mco row renders its methodology note where
    /// every other absent row renders an em-dash: the wall-clock rule is a
    /// DECISION about how the board will be measured, and it must be readable
    /// before the sweep lands rather than only after -- otherwise the
    /// methodology becomes visible exactly when it no longer needs defending.
    #[test]
    fn an_absent_mco_row_still_states_the_wall_clock_rule() {
        let c = ctx(
            &[
                ("ipc7-mco-t4", "seq-mco t4", &["m5-air"]),
                ("ipc67-temporal", "tempo-sat", &["m5-air"]),
            ],
            "m5-air",
        );
        let out = render(&c);
        assert!(
            out.contains(&format!(
                "| seq-mco t4 | sweep in flight / not yet run | — | {MCO_QUALITY} | — |"
            )),
            "{out}"
        );
        // ...and its neighbours, which have no such decision to state, do not.
        assert!(
            out.contains("| tempo-sat | sweep in flight / not yet run | — | — | — |"),
            "{out}"
        );
    }

    /// The rows that are not boards render whatever the data says: the two
    /// reference-scored preference boards and the `tempo-opt` exclusion are
    /// prose about a decision, and they must appear even on a box holding no
    /// raws at all. A table that hides them reads as a table that forgot them.
    #[test]
    fn the_fixed_rows_render_without_any_raw() {
        let out = render(&ctx(&[], "m5-air"));
        assert!(out.contains("| complex-preferences | no (modal operators rejected by name) |"));
        assert!(out.contains(TEMPO_OPT_ROW));
        assert!(out.contains("[`ipc5-scoreboard.md`](ipc5-scoreboard.md)"));
    }

    /// The document's frame is not conditional on data: four sections, four
    /// tables, the preamble and the closing note, on a box that has swept
    /// nothing. A generator that emits a shorter document when a sweep is
    /// incomplete is the destructive-overwrite hazard in another form.
    #[test]
    fn the_frame_renders_on_a_box_holding_no_raws() {
        let out = render(&ctx(&[], "m5-air"));
        for section in [SECTION_IPC5, SECTION_IPC6, SECTION_IPC7, SECTION_MODERN] {
            assert!(out.contains(section), "missing {section}");
        }
        assert_eq!(out.matches(TABLE_HEAD[1]).count(), 4);
        assert!(out.starts_with(DOC_HEADER[0]));
        assert!(out.ends_with(&format!("{MODERN_FOOTNOTE}\n\n")));
    }

    /// The variation selector, defended where it is typed. The one `entered`
    /// cell with an inline glyph cannot go through `glyph::SCALES` (it is a
    /// `const`), so this is the check that keeps the two spellings identical.
    #[test]
    fn the_inline_scales_literal_matches_the_glyph() {
        assert!(
            ENTERED_2026_OPT.ends_with(&format!("{})", glyph::SCALES)),
            "the 0.21 -opt entry cell must carry the two-codepoint proof glyph: {ENTERED_2026_OPT:?}"
        );
        assert!(ENTERED_2026_OPT
            .as_bytes()
            .ends_with(b"\xe2\x9a\x96\xef\xb8\x8f)"));
        let (_, _, entered) = MODERN_ROWS
            .iter()
            .find(|(label, _, _)| *label == "2026 numeric-opt")
            .expect("the 2026 -opt pairs row is in the render list");
        assert_eq!(*entered, ENTERED_2026_OPT);
    }

    /// Every label the renderer asks for must exist as a board somewhere, or
    /// the row is permanently absent for a reason no reader can see. This is
    /// the 0.20 `ipc2026-numeric` incident in reverse: there, a board existed
    /// with no render entry; here, a render entry with a typo'd label would
    /// print "sweep in flight" forever.
    #[test]
    fn every_rendered_label_names_a_manifest_board() {
        let src = std::fs::read_to_string(manifest_path());
        let Ok(src) = src else {
            eprintln!("SKIP: benchmarks/manifest.toml absent");
            return;
        };
        let m = crate::manifest::Manifest::parse(&src, "manifest.toml").expect("parses");
        let mut wanted: Vec<&str> = Vec::new();
        wanted.extend(IPC5_ROWS.iter().map(|(l, _, _)| *l));
        wanted.extend(IPC6_TRACKS.iter().copied());
        wanted.extend(IPC7_TRACKS.iter().copied());
        wanted.extend(IPC7_MCO.iter().copied());
        wanted.push("seq-opt");
        wanted.extend(MODERN_ROWS.iter().map(|(l, _, _)| *l));
        for label in wanted {
            assert!(
                m.board_by_label(label).is_some(),
                "render list names \"{label}\", which no [[board]] publishes under"
            );
        }
    }

    /// The mirror: a board in the manifest that no section renders is a sweep
    /// whose results cannot reach the table. Exactly the 0.20 incident.
    #[test]
    fn every_manifest_board_is_rendered_somewhere() {
        let src = std::fs::read_to_string(manifest_path());
        let Ok(src) = src else {
            eprintln!("SKIP: benchmarks/manifest.toml absent");
            return;
        };
        let m = crate::manifest::Manifest::parse(&src, "manifest.toml").expect("parses");
        let mut rendered: Vec<&str> = Vec::new();
        rendered.extend(IPC5_ROWS.iter().map(|(l, _, _)| *l));
        rendered.extend(IPC6_TRACKS.iter().copied());
        rendered.extend(IPC7_MCO.iter().copied());
        rendered.push("seq-opt");
        rendered.extend(MODERN_ROWS.iter().map(|(l, _, _)| *l));
        for b in &m.boards {
            assert!(
                rendered.contains(&b.label.as_str()),
                "board \"{}\" is swept but appears in no section of ipc-standings.md",
                b.label
            );
        }
    }

    fn manifest_path() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../benchmarks/manifest.toml")
    }
}
