//! The generated block inside `README.md`. Port of `_patch_readme` (:703-743).
//!
//! Hand-maintained numbers on a front page drift the moment a sweep lands, and
//! a stale headline is worse than none -- so the shop window is generated from
//! the same data as the table behind it, and [`block`] shares
//! [`RenderCtx::standings`] with `STANDINGS.md` so the two cannot disagree
//! about which boards are in the headline.
//!
//! **The links are ABSOLUTE, and that is an incident.** This block is generated
//! into `README.md`, which ships as the crate README (`readme =
//! "../../README.md"`). crates.io and docs.rs resolve relative links against
//! the CRATE directory, so a bare `STANDINGS.md` there resolves to
//! `crates/ferroplan/STANDINGS.md` and 404s on the published page. Every other
//! link in that README is absolute for the same reason.
//!
//! **[`patch`] never rewrites a README it cannot find both markers in.** It
//! returns `None`, and the caller leaves the file exactly as it was. The
//! alternative -- splicing at whatever offset a failed search produced -- is
//! how a front page gets truncated by a tool that was only asked for a number.

use crate::fmt::{self, glyph};
use crate::render::RenderCtx;

/// The opening marker. Deliberately NOT the whole comment: the marker line
/// carries a "generated by ...; do not hand-edit" note after it, and the splice
/// keeps whatever that note currently says rather than reasserting it.
pub const README_BEGIN: &str = "<!-- STANDINGS:BEGIN";
/// The closing marker, whole.
pub const README_END: &str = "<!-- STANDINGS:END -->";

/// The absolute link prefix. Belongs in `benchmarks/manifest.toml` beside the
/// boards -- it is a fact about where this project is published, not about how
/// a table is drawn -- and lives here until `[[board]]`'s file carries a
/// `gh_blob` key. See the module header for why it cannot become a relative
/// path.
pub const GH_BLOB: &str = "https://github.com/hhh42/ferroplan/blob/main/";

/// How many boards the front page shows. "Best five shown" is printed under
/// the table, so the two must move together.
const TOP_N: usize = 5;

/// The front page's bar is narrower than `STANDINGS.md`'s -- 16 cells, not 20.
const README_BAR_WIDTH: usize = 16;

/// Build the block that goes between the markers.
///
/// `None` when no board is live: Python's `if not os.path.exists(p) or not
/// tot_n: return` leaves the README untouched rather than replacing a headline
/// with an empty one. A box holding no raws must not blank the front page.
///
/// The returned string both starts and ends with a newline, because the joined
/// list does -- it is spliced directly after the `-->` of the opening marker and
/// directly before the closing marker, and those two newlines are what put each
/// marker on its own line.
pub fn block(ctx: &RenderCtx) -> Option<String> {
    let st = ctx.standings();
    if st.total_rows == 0 {
        return None;
    }

    let mut l: Vec<String> = Vec::new();
    l.push(String::new());

    // No plural switch here, unlike `STANDINGS.md`: the Python's front-page
    // headline says "boards" unconditionally. Ported as written -- the shape of
    // the sentence is published text, and a one-board repository is not a state
    // this project has been in since 0.14.
    let mut headline = format!(
        "**{}% coverage across {} IPC boards** ({}/{}) on `{}`",
        fmt::fmt_f(fmt::pct(st.total_solved, st.total_rows), 0),
        st.live.len(),
        fmt::thousands(st.total_solved as u64),
        fmt::thousands(st.total_rows as u64),
        ctx.box_id.as_str(),
    );
    if st.proofs > 0 {
        headline.push_str(&format!(
            ", including **{} certified optima**.",
            fmt::thousands(st.proofs as u64)
        ));
    } else {
        headline.push('.');
    }
    l.push(headline);

    l.push(String::new());
    l.push("| track | coverage | |".to_string());
    l.push("|---|---|---|".to_string());
    for r in st.live.iter().take(TOP_N) {
        l.push(format!(
            "| {}{} | {}/{} | `{}` {}% |",
            r.label,
            ctx.proof_mark(r.label),
            r.solved,
            r.total,
            fmt::bar(r.pct, README_BAR_WIDTH),
            fmt::fmt_f(r.pct, 0),
        ));
    }

    l.push(String::new());
    l.push(format!(
        "Best five shown. **[Full standings {} `STANDINGS.md`]({GH_BLOB}STANDINGS.md)** {} \
         per-track detail, quality scoring and failure classes in \
         [`benchmarks/ipc-standings.md`]({GH_BLOB}benchmarks/ipc-standings.md).",
        glyph::ARROW,
        glyph::MIDDOT,
    ));
    l.push(String::new());

    Some(l.join("\n"))
}

/// Splice `block` between the README's markers, returning the new text.
///
/// `None` means NOTHING WAS PATCHED and the caller must leave the file alone --
/// the Python's two bare `return`s, which leave the text on disk unchanged.
/// There are three ways to get it, and all three are refusals rather than
/// best-effort writes:
///
/// * either marker is missing (`text.find(...) < 0`);
/// * the opening marker's comment is never closed, so there is no `-->` to
///   splice after. Python computes `text.find("-->", i) + 3` and gets `2` from
///   the miss, then writes `text[:2] + block + text[j:]` -- which deletes the
///   README down to its third byte. That is not a number this port has to
///   reproduce;
/// * the closing marker sits before the end of the opening one, which would
///   splice the block into the middle of its own marker.
///
/// Indices are BYTES, from `str::find`, exactly as Python's `str.find` returns
/// byte offsets into an already-decoded string here. Both markers and `-->` are
/// pure ASCII, so every offset lands on a character boundary by construction.
pub fn patch(readme_text: &str, block: &str) -> Option<String> {
    let i = readme_text.find(README_BEGIN)?;
    let j = readme_text.find(README_END)?;
    let head_end = readme_text[i..].find("-->").map(|k| i + k + 3)?;
    if j < head_end {
        return None;
    }
    let mut out = String::with_capacity(readme_text.len() + block.len());
    out.push_str(&readme_text[..head_end]);
    out.push_str(block);
    out.push_str(&readme_text[j..]);
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::tests_support::empty_ctx;

    const README: &str = "# ferroplan\n\
                          \n\
                          <!-- STANDINGS:BEGIN — generated; do not hand-edit -->\n\
                          old headline\n\
                          <!-- STANDINGS:END -->\n\
                          \n\
                          ## Install\n";

    /// The ordinary splice: the block replaces everything between the two
    /// markers, and both markers survive with their own lines intact.
    #[test]
    fn splices_between_the_markers() {
        let out = patch(README, "\nnew headline\n").expect("both markers present");
        assert_eq!(
            out,
            "# ferroplan\n\
             \n\
             <!-- STANDINGS:BEGIN — generated; do not hand-edit -->\n\
             new headline\n\
             <!-- STANDINGS:END -->\n\
             \n\
             ## Install\n"
        );
    }

    /// A missing marker leaves the file alone. `None` is the whole answer: the
    /// caller writes nothing, so the README is unchanged. Splicing at a failed
    /// search's offset is how a front page gets truncated by a tool that was
    /// only asked for a number.
    #[test]
    fn a_missing_marker_patches_nothing() {
        let no_begin = "# ferroplan\n<!-- STANDINGS:END -->\n";
        let no_end = "# ferroplan\n<!-- STANDINGS:BEGIN -->\n";
        let neither = "# ferroplan\n\nnothing generated here.\n";
        assert!(patch(no_begin, "\nx\n").is_none());
        assert!(patch(no_end, "\nx\n").is_none());
        assert!(patch(neither, "\nx\n").is_none());
    }

    /// An opening marker whose comment is never closed has no `-->` to splice
    /// after. Python would write `text[:2] + block + text[j:]` here and take
    /// the README with it.
    #[test]
    fn an_unterminated_opening_marker_patches_nothing() {
        let broken = "# ferroplan\n<!-- STANDINGS:BEGIN oops\n<!-- STANDINGS:END --\n";
        assert!(patch(broken, "\nx\n").is_none());
    }

    /// Markers in the wrong order would splice the block into the middle of the
    /// opening marker itself.
    #[test]
    fn markers_out_of_order_patch_nothing() {
        let reversed = "<!-- STANDINGS:END -->\n<!-- STANDINGS:BEGIN x -->\n";
        assert!(patch(reversed, "\nx\n").is_none());
    }

    /// A multi-byte character before the markers must not shift the splice: the
    /// offsets are BYTES and the text is sliced by bytes, so an em dash in the
    /// heading above the block is invisible to the arithmetic.
    #[test]
    fn multibyte_text_before_the_block_does_not_shift_the_splice() {
        let text =
            "# ferroplan — a planner\n<!-- STANDINGS:BEGIN -->\nold\n<!-- STANDINGS:END -->\n";
        let out = patch(text, "\nnew\n").expect("markers present");
        assert_eq!(
            out,
            "# ferroplan — a planner\n<!-- STANDINGS:BEGIN -->\nnew\n<!-- STANDINGS:END -->\n"
        );
    }

    /// With nothing live there is no block, so the front page keeps whatever it
    /// last said. A box holding no raws must not blank the headline.
    #[test]
    fn no_live_boards_means_no_block() {
        assert!(block(&empty_ctx()).is_none());
    }

    /// The published links must be absolute. A relative `STANDINGS.md` resolves
    /// against the CRATE directory on crates.io and docs.rs -- it 404s on the
    /// page most readers actually see.
    #[test]
    fn the_links_are_absolute() {
        assert!(GH_BLOB.starts_with("https://"));
        assert!(GH_BLOB.ends_with('/'));
    }
}
