//! `STANDINGS.md` -- the at-a-glance view. Port of `write_summary` (:583-701).
//!
//! `ipc-standings.md` is the reference table: every track, every failure class,
//! five columns of prose. Correct, and useless for the question "roughly where
//! are we?". This answers that question and links there for the detail.
//!
//! Three rules here are incidents, not layout.
//!
//! **The delta column obeys one law: a snapshot is only compared against a
//! predecessor measured on the SAME BOX.** Faster silicon inflates coverage at
//! a fixed budget, so a cloud-to-Air "improvement" would be pure hardware.
//! Where no comparable predecessor exists the column says so instead of
//! inventing a number. The law is enforced by the type -- the only way to hold
//! a comparable predecessor is [`History::comparable_predecessor`], which is
//! also where the second half lives: the PREVIOUS RELEASE by version, never the
//! most recently MEASURED snapshot. A backfilled old tag is measured late (0.19
//! was re-swept after 0.20 shipped), and picking by date silently compares a
//! release to its grandparent. On 2018-sat that is the difference between +7
//! and +17.
//!
//! **The buckets sort by percentage DESCENDING with a STABLE sort.** Ties keep
//! manifest order, so two boards that land on the same share cannot swap places
//! between runs. `sort_by`, never `sort_unstable_by` -- a reordered pair is a
//! diff in a published table with no number wrong to point at.
//!
//! **Cloud-era boards are excluded from the headline total.** They are not
//! comparable to the boards above them; averaging the two would launder a
//! hardware change into a result. They get their own section saying exactly
//! that, because dropping them silently would claim we never measured them.
//!
//! Section prose and the bucket thresholds below belong in
//! `benchmarks/manifest.toml` beside the boards they describe; see the note on
//! `BANDS` and the module header of [`super::detail`].
//!
//! [`History::comparable_predecessor`]: crate::history::History::comparable_predecessor

use crate::fmt::{self, glyph};
use crate::history::delta_cell;
use crate::render::RenderCtx;

// ===========================================================================
// THE SKELETON -- belongs in benchmarks/manifest.toml; see the module header.
// ===========================================================================

const TITLE: &str = "# Where ferroplan stands";

const GENERATED_BY: &str = "Generated by `python3 benchmarks/standings.py` — do not hand-edit. \
                            Per-track detail, quality scoring and failure classes: \
                            [`benchmarks/ipc-standings.md`](benchmarks/ipc-standings.md).";

/// The coverage buckets, as `(name, inclusive lower bound)`, in DESCENDING
/// order. Each band's upper bound is the previous band's lower bound, which is
/// how the Python's three lambdas (`p >= 60`, `25 <= p < 60`, `p < 25`) are
/// expressed without three chances to leave a gap between them.
///
/// The last band's floor is negative infinity rather than zero, so a percentage
/// that should be impossible still lands somewhere visible instead of vanishing
/// out of the bottom of the document.
const BANDS: &[(&str, f64)] = &[
    ("Strong", 60.0),
    ("Middle", 25.0),
    ("Weak", f64::NEG_INFINITY),
];

const BAND_HEAD: &[&str] = &[
    "| track | coverage | | vs previous | vs field |",
    "|---|---|---|---|---|",
];

const PENDING_HEADING: &str = "## Awaiting promotion";
const PENDING_PROSE: &str = "Swept on this box but not yet promoted into the table — a sweep \
                             still in flight, or boards written but not published. Not a \
                             measurement gap.";

const CLOUD_HEADING: &str = "## Not re-baselined";
const CLOUD_PROSE: &str = "These still carry numbers from the previous machine. They are NOT \
                           comparable to the boards above and are excluded from the headline \
                           total — the old numbers stay in git history.";

// ===========================================================================
// The renderer
// ===========================================================================

/// Render `STANDINGS.md`.
///
/// Returns a `String`; writes nothing. See [`super`] on why that is a rule.
pub fn render(ctx: &RenderCtx) -> String {
    let st = ctx.standings();
    let prev = ctx.predecessor();

    let mut l: Vec<String> = vec![TITLE.to_string(), String::new()];

    // The headline is skipped entirely when nothing is live -- a "0% across 0
    // boards" banner would be a measurement claim made out of an empty
    // directory.
    if st.total_rows > 0 {
        let plural = if st.live.len() == 1 {
            "board"
        } else {
            "boards"
        };
        l.push(format!(
            "**{}% coverage across {} IPC {plural}** ({}/{}), measured on `{}`.",
            fmt::fmt_f(fmt::pct(st.total_solved, st.total_rows), 0),
            st.live.len(),
            fmt::thousands(st.total_solved as u64),
            fmt::thousands(st.total_rows as u64),
            ctx.box_id.as_str(),
        ));
        if st.proofs > 0 {
            l.push(String::new());
            l.push(format!(
                "Of those, **{} are certified optima** — on the optimal tracks coverage IS \
                 proof rate, so a solved row is a proof, not a plan.",
                fmt::thousands(st.proofs as u64)
            ));
        }
    }
    l.push(String::new());
    l.push(GENERATED_BY.to_string());
    l.push(String::new());

    for (i, (name, lo)) in BANDS.iter().enumerate() {
        // Open at the top, and each band's ceiling is the floor above it.
        let hi = if i == 0 {
            f64::INFINITY
        } else {
            BANDS[i - 1].1
        };
        let band: Vec<_> = st
            .live
            .iter()
            .filter(|r| r.pct >= *lo && r.pct < hi)
            .collect();
        // An empty band prints NOTHING -- not an empty table. A heading with no
        // rows under it reads as boards that went missing.
        if band.is_empty() {
            continue;
        }
        l.push(format!("## {name}"));
        l.push(String::new());
        l.extend(BAND_HEAD.iter().map(|s| (*s).to_string()));
        for r in band {
            l.push(format!(
                "| {}{} | {}/{} | `{}` {}% | {} | {} |",
                r.label,
                ctx.proof_mark(r.label),
                r.solved,
                r.total,
                fmt::bar(r.pct, fmt::BAR_WIDTH),
                fmt::fmt_f(r.pct, 0),
                delta_cell(prev.as_ref(), r.label, r.solved, r.total),
                ctx.field
                    .cell(r.label, r.rows, &ctx.referee, r.solved, r.total),
            ));
        }
        l.push(String::new());
    }

    if !st.pending.is_empty() {
        l.push(PENDING_HEADING.to_string());
        l.push(String::new());
        l.push(PENDING_PROSE.to_string());
        l.push(String::new());
        l.push(name_list(&st.pending));
        l.push(String::new());
    }
    if !st.cloud.is_empty() {
        l.push(CLOUD_HEADING.to_string());
        l.push(String::new());
        l.push(CLOUD_PROSE.to_string());
        l.push(String::new());
        l.push(name_list(&st.cloud));
        l.push(String::new());
    }

    l.extend(how_to_read());

    // `"\n".join(L) + "\n"` -- the list ends with an empty string, so the file
    // ends with a blank line. That byte is in the committed artifact.
    let mut out = l.join("\n");
    out.push('\n');
    out
}

/// A middot-joined list of board names, sorted.
///
/// Python builds `"`{c}` · "` for each and then `.rstrip(" ·")`, which strips
/// trailing spaces AND middots -- so the last separator disappears and the
/// closing backtick survives. Reproduced literally rather than by joining,
/// because the two differ the moment a name ends in a middot and the literal
/// form is the one that is published.
///
/// `sort` is byte order, which is Python's codepoint order for `sorted()` --
/// UTF-8 is order-preserving, so the two agree by construction.
fn name_list(names: &[&str]) -> String {
    let mut sorted: Vec<&str> = names.to_vec();
    sorted.sort_unstable();
    let mut s = String::new();
    for c in sorted {
        s.push('`');
        s.push_str(c);
        s.push_str("` ");
        s.push_str(glyph::MIDDOT);
        s.push(' ');
    }
    // `rstrip(" ·")` is a CHARACTER SET, not a suffix: it eats the trailing
    // space, the middot and the space before it, and stops at the backtick.
    s.trim_end_matches([' ', '\u{00b7}']).to_string()
}

/// The reading guide. Built with `format!` rather than as a `const` so that
/// EVERY non-ASCII character in it is spelled through [`glyph`] and never typed
/// twice: the proof scales (two codepoints), the multiplication sign, the
/// not-equal sign, and BOTH em dashes -- the one that separates the caveat
/// clause as well as the one that means "no data held". Each has a look-alike
/// that renders almost identically and diffs on every regeneration, and a
/// literal typed inline here is exactly how one of them would get away with it.
/// (The `const` prose above this function still hand-types its em dashes; those
/// are single occurrences the golden battery pins byte for byte.)
fn how_to_read() -> Vec<String> {
    vec![
        "## How to read this".to_string(),
        String::new(),
        "- **coverage** is solved/total at that track's official-ish budget (60 s \
         satisficing, 60 s temporal, 300 s where marked an entry)."
            .to_string(),
        format!(
            "- **{} marks a proof track**: coverage is the share of instances PROVEN \
             optimal, a far harder bar than finding some plan.",
            glyph::SCALES
        ),
        "- **vs previous** compares only against a release measured on the same hardware. \
         A blank means no comparable predecessor exists yet, not zero movement."
            .to_string(),
        format!(
            "- **vs field** is a rough coverage-RATE placement against that competition's \
             actual entrants (data: `benchmarks/field-results.json` + the vendored official \
             IPC-2023n CSVs), under the standing caveats {} official budgets are ~30{} ours, \
             and coverage {} IPC's quality-weighted scoring. `~` marks a field with \
             unlocated entrants; `{}` means no per-entrant field data is held. Prose and \
             provenance: [`docs/ipc-rankings.md`](docs/ipc-rankings.md).",
            glyph::EM_DASH,
            glyph::TIMES,
            glyph::NE,
            glyph::EM_DASH
        ),
        "- A board is only as honest as its conditions; those are recorded per cycle in \
         `docs/roadmap-0.N.md`."
            .to_string(),
        String::new(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::tests_support::empty_ctx;

    /// An empty band renders NOTHING, not a heading over an empty table. A
    /// heading with no rows under it reads as boards that went missing between
    /// runs, which is the opposite of what an empty band means.
    #[test]
    fn an_empty_band_prints_no_heading() {
        // No boards at all: every band is empty and the headline is suppressed.
        let ctx = empty_ctx();
        let out = render(&ctx);
        assert!(!out.contains("## Strong"), "{out}");
        assert!(!out.contains("## Middle"), "{out}");
        assert!(!out.contains("## Weak"), "{out}");
        // ...and the document still renders its frame, so a box holding no raws
        // produces a readable page rather than a blank one.
        assert!(out.starts_with("# Where ferroplan stands\n"));
        assert!(out.contains("## How to read this"));
    }

    /// With nothing live there is no headline: "0% coverage across 0 IPC
    /// boards" would be a measurement claim assembled out of an empty
    /// directory.
    #[test]
    fn no_live_boards_means_no_headline() {
        let out = render(&empty_ctx());
        assert!(!out.contains("% coverage across"), "{out}");
    }

    /// The bands must tile the whole range with no gap and no overlap: every
    /// percentage lands in exactly one. A board that falls between two bands
    /// disappears from a published summary while still counting in its total.
    #[test]
    fn the_bands_tile_the_whole_range() {
        for p in [-1.0, 0.0, 24.9, 25.0, 59.9, 60.0, 99.9, 100.0, 101.0] {
            let hits = BANDS
                .iter()
                .enumerate()
                .filter(|(i, (_, lo))| {
                    let hi = if *i == 0 {
                        f64::INFINITY
                    } else {
                        BANDS[i - 1].1
                    };
                    p >= *lo && p < hi
                })
                .count();
            assert_eq!(hits, 1, "{p} lands in {hits} bands");
        }
    }

    /// The band edges are the Python's, exactly: 60 is Strong (not Middle), 25
    /// is Middle (not Weak). Both boundaries are inclusive at the bottom.
    #[test]
    fn band_edges_are_inclusive_at_the_floor() {
        let band_of = |p: f64| {
            BANDS
                .iter()
                .enumerate()
                .find(|(i, (_, lo))| {
                    let hi = if *i == 0 {
                        f64::INFINITY
                    } else {
                        BANDS[i - 1].1
                    };
                    p >= *lo && p < hi
                })
                .map(|(_, (n, _))| *n)
                .unwrap()
        };
        assert_eq!(band_of(60.0), "Strong");
        assert_eq!(band_of(59.999), "Middle");
        assert_eq!(band_of(25.0), "Middle");
        assert_eq!(band_of(24.999), "Weak");
    }

    /// `rstrip(" ·")` drops the trailing separator and keeps the closing
    /// backtick. A plain `join` would agree here and disagree on a name ending
    /// in a middot, so the literal form is the one ported.
    #[test]
    fn the_name_list_loses_only_its_trailing_separator() {
        assert_eq!(name_list(&["b", "a"]), "`a` · `b`");
        assert_eq!(name_list(&["only"]), "`only`");
        assert_eq!(name_list(&[]), "");
    }
}
