//! @generated by ggen from `.ggen/ferroplan-v26.8.1/ontology.ttl`.
//!
//! Do not hand-edit. Change the ontology/query/template and run `ggen sync run`.

use serde::{Deserialize, Serialize};

#[cfg(feature = "schema")]
use schemars::JsonSchema;

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[serde(rename_all = "kebab-case")]
pub enum PlanningRail {
    Deterministic,
    Probabilistic,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Default)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[serde(rename_all = "kebab-case")]
pub enum PolicySearch {
    #[default]
    Auto,
    BackwardInduction,
    ValueIteration,
    LaoStar,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Standing {
    PartialAlive,
    Alive,
    Blocked,
    BuildBroken,
    Unknown,
    Unsupported,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum StandingReason {
    NoReplay,
    ConvergenceLimit,
    DependencyMissing,
    MockedValidator,
    ConstraintViolation,
    PolicyNotClosed,
    ObservationIncomplete,
    OutcomeNotAdmitted,
    VerifierDisagreement,
    ResourceLimit,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[serde(tag = "kind", content = "threshold", rename_all = "kebab-case")]
pub enum RiskConstraint {
    MinimumGoalProbability(f64),
    MaximumUnsafeReachability(f64),
    MinimumExpectedReward(f64),
    MaximumExpectedCost(f64),
}

impl RiskConstraint {
    pub fn validate(&self) -> Result<(), String> {
        match self {
            Self::MinimumGoalProbability(value)
            | Self::MaximumUnsafeReachability(value) => {
                if !value.is_finite() || !(0.0..=1.0).contains(value) {
                    return Err("probability thresholds must be finite and in [0,1]".into());
                }
            }
            Self::MinimumExpectedReward(value) | Self::MaximumExpectedCost(value) => {
                if !value.is_finite() {
                    return Err("reward/cost thresholds must be finite".into());
                }
            }
        }
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
pub struct ValueInterval {
    pub lower: f64,
    pub upper: f64,
}

impl ValueInterval {
    pub fn exact(value: f64) -> Self {
        Self {
            lower: value,
            upper: value,
        }
    }

    pub fn width(self) -> f64 {
        self.upper - self.lower
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
pub struct ConstraintVerdict {
    pub constraint: RiskConstraint,
    pub satisfied: bool,
    pub observed: ValueInterval,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[serde(rename_all = "kebab-case")]
pub enum PolicyCounterexampleKind {
    UnknownState,
    MissingDecision,
    ProbabilityMass,
    UnknownSuccessor,
    BellmanResidual,
    UnsafeThreshold,
    RewardThreshold,
    StructuralMismatch,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
pub struct PolicyCounterexample {
    pub kind: PolicyCounterexampleKind,
    pub state: Option<usize>,
    pub message: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
pub struct PolicyVerificationReport {
    pub standing: Standing,
    pub valid: bool,
    pub model_digest: String,
    pub policy_digest: String,
    pub closure: bool,
    pub bellman_residual: f64,
    pub goal_probability: ValueInterval,
    pub unsafe_probability: ValueInterval,
    pub expected_reward: ValueInterval,
    pub constraints: Vec<ConstraintVerdict>,
    pub counterexamples: Vec<PolicyCounterexample>,
    pub reason: Option<StandingReason>,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PolicySessionPhase {
    Created,
    Ready,
    ActionSelected,
    AwaitingObservation,
    ObservationRequired,
    Drifted,
    Blocked,
    Closed,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
pub struct PolicySessionStatus {
    pub phase: PolicySessionPhase,
    pub current_state: Option<usize>,
    pub remaining: Option<usize>,
    pub selected_action: Option<String>,
    pub policy_valid: bool,
    pub predecessor_receipt: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
pub struct PolicyExplanation {
    pub state: usize,
    pub remaining: Option<usize>,
    pub terminal: bool,
    pub chosen_action: Option<String>,
    pub value: Option<f64>,
    pub goal_probability: ValueInterval,
    pub unsafe_probability: ValueInterval,
    pub expected_reward: ValueInterval,
    pub successors: Vec<crate::PolicyOutcome>,
    pub notes: Vec<String>,
}
