#!/usr/bin/env bash
# Regenerate the phase-1 generated workflows from ontology/ferroplan-ci.ttl via github-actions-pack.
# Usage: scripts/ci_gen.sh           regenerate + install into .github/workflows/
#        scripts/ci_gen.sh --check   regenerate to staging only; fail if installed files differ
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
gen="$root/scripts/ci_gen"
files="ci planning-runtime ecosystem-alive-format-closure daily-agent-methods ferroplan-harvester"
if [ "${1:-}" = "--check" ] && ! cmp -s "$root/ontology/ferroplan-ci.ttl" "$gen/ontology/ferroplan-ci.ttl"; then
  echo "CI_ONTOLOGY_COPY_DRIFT: scripts/ci_gen/ontology/ferroplan-ci.ttl != ontology/ferroplan-ci.ttl (run scripts/ci_gen.sh to resync)" >&2
  exit 1
fi
cp "$root/ontology/ferroplan-ci.ttl" "$gen/ontology/ferroplan-ci.ttl"
rm -rf "$gen/.github"
(cd "$gen" && ggen sync run >/dev/null 2>&1)
for f in $files; do
  head -1 "$gen/.github/workflows/$f.yml" | grep -q '^# GENERATED by ggen' \
    || { echo "missing provenance header: $f.yml" >&2; exit 1; }
  python3 -c 'import sys,yaml; yaml.safe_load(open(sys.argv[1]))' "$gen/.github/workflows/$f.yml"
  if [ "${1:-}" = "--check" ]; then
    cmp "$gen/.github/workflows/$f.yml" "$root/.github/workflows/$f.yml"
  else
    cp "$gen/.github/workflows/$f.yml" "$root/.github/workflows/$f.yml"
  fi
done
rm -rf "$gen/.github"
