#!/usr/bin/env python3
"""PreToolUse hook: refuse hand-edits of ontology-generated files.

The ontology at plugins/chatman-ecosystem/ontology/ferroplan-domain.ttl is
meant to be the single source of truth for certain generated source files.
Hand-patching a generated file instead of fixing the ontology/template and
regenerating is the exact anti-pattern this hook exists to catch (it was
found for real in the sibling project ~/claude-code-config-lsp, where
src/capabilities.rs is hand-edited because its own ggen-based regeneration is
currently broken upstream).

crates/ferroplan-mcp's MCP tool resource text (the `*_ONTOLOGY` constants in
main.rs / bin/*.rs) is also ontology-generated, via crates/ferroplan-mcp/build.rs
at compile time — but deliberately NOT via a checked-in generated .rs file.
build.rs writes those constants to $OUT_DIR under target/, which is never
committed and has no path a human could open and hand-edit in this repo. That
class of generated output needs no entry in GENERATED_PATHS and no hook
coverage: the mechanism that would make hand-patching possible (a tracked
file) doesn't exist for it. GENERATED_PATHS below only needs entries for
generated output that IS checked into the repo, like the wasm shims.

Scope of this first implementation: a simple mtime comparison between the
ontology file and the target generated file. This is an honestly-scoped
starting point, not a receipt chain — a stronger follow-up would wire this
into the same BLAKE3/ggen-sync-receipt machinery loop.py uses for protected
Bash actuation, once a ggen-sync-receipt pipeline actually exists for
generated source.

Protocol: reads the PreToolUse hook JSON payload from stdin, and on Edit/Write
calls whose file_path is a known generated path, denies the edit (via
hookSpecificOutput.permissionDecision = "deny") unless the ontology file's
mtime is newer than the target file's mtime. Always exits 0; the deny/allow
decision is communicated via the JSON payload printed to stdout, matching the
convention used by scripts/loop.py's `hook` subcommand.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

# Paths (relative to the repository root) that are generated from the
# ontology and must never be hand-patched directly.
#
# crates/ferroplan-mcp's MCP tool resource text is intentionally NOT listed
# here: it's generated by build.rs into $OUT_DIR, never checked into the
# repo, so there is no tracked path for a human to hand-patch in the first
# place (see the module docstring).
GENERATED_PATHS = (
    "crates/ferroplan-wasm/src/lib.rs",
)

ONTOLOGY_PATH = "plugins/chatman-ecosystem/ontology/ferroplan-domain.ttl"


def read_hook_input() -> dict:
    raw = sys.stdin.read()
    if not raw.strip():
        return {}
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as error:
        raise SystemExit(f"invalid hook input: {error}") from error
    if not isinstance(value, dict):
        raise SystemExit("hook input must be a JSON object")
    return value


def deny(reason: str) -> int:
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    return 0


def main() -> int:
    payload = read_hook_input()
    if payload.get("hook_event_name") != "PreToolUse":
        return 0
    if payload.get("tool_name") not in {"Edit", "Write"}:
        return 0

    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return 0
    file_path = tool_input.get("file_path")
    if not isinstance(file_path, str) or not file_path:
        return 0

    cwd = str(payload.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
    root = Path(cwd).resolve()

    try:
        target_abs = Path(file_path).resolve()
        target_rel = target_abs.relative_to(root).as_posix()
    except ValueError:
        return 0

    if target_rel not in GENERATED_PATHS:
        return 0

    ontology_abs = root / ONTOLOGY_PATH
    if not ontology_abs.exists():
        return deny(
            "GENERATED_FILE_GUARD: "
            f"{target_rel} is generated from the ontology at {ONTOLOGY_PATH}, "
            "but the ontology file could not be found to check freshness. "
            "Edit the ontology (and its generator/template), regenerate, then "
            "retry — do not hand-patch the generated file."
        )

    if not target_abs.exists():
        # Nothing generated yet; allow (e.g. first-time generation writing
        # the file directly is outside this hook's concern — this hook only
        # protects against re-hand-editing an existing generated artifact).
        return 0

    ontology_mtime = ontology_abs.stat().st_mtime
    target_mtime = target_abs.stat().st_mtime

    if ontology_mtime > target_mtime:
        # Ontology changed more recently than the generated file: treat this
        # as "a regeneration is due/in flight," not proof that this specific
        # edit is a regeneration. Still allow it — a stronger receipt-based
        # check would distinguish "edited by the generator" from "edited by
        # hand" here.
        return 0

    return deny(
        "GENERATED_FILE_GUARD: "
        f"{target_rel} is generated from the ontology at {ONTOLOGY_PATH} and "
        "must not be hand-patched. The ontology file is not newer than this "
        "generated file, so this edit looks like a direct hand-patch rather "
        "than a regeneration. Instead: edit the ontology (and its generator "
        "template) to express the change, regenerate the file, then retry. "
        "(This is an mtime-based check, not a full receipt chain — see the "
        "module docstring for the honestly-scoped follow-up.)"
    )


if __name__ == "__main__":
    raise SystemExit(main())
